version: '3'

services:
  ioc:
    image: ${CI_REGISTRY_IMAGE:-registry.gitlab.com/nsf-noirlab/gemini/rtsw/iocs/subaru-sensor-data}/ioc:${CI_COMMIT_REF_SLUG:-master}
    network_mode: host
    environment:
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - EPICS_CA_ADDR_LIST=localhost
      - EPICS_PVA_ADDR_LIST=0.0.0.0
      - EPICS_PVA_AUTO_ADDR_LIST=NO
      - EPICS_PVA_BROADCAST_PORT=5076
      - EPICS_PVA_SERVER_PORT=5075
    volumes:
      - ./ioc:/app
    restart: unless-stopped

  web:
    image: ${CI_REGISTRY_IMAGE:-registry.gitlab.com/nsf-noirlab/gemini/rtsw/iocs/subaru-sensor-data}/web:${CI_COMMIT_REF_SLUG:-master}
    ports:
      - "8000:8000"
    depends_on:
      - ioc
    environment:
      - IOC_HOST=localhost
      - IOC_PORT=5076
    volumes:
      - ./web:/app
    restart: unless-stopped 